services:
  porkcron:
    build: .
    container_name: porkcron
    env_file: .env
    volumes:
      - ssl:/etc/porkcron

  # uncomment if you're running nginx:
  # nginx:
  #   build: ../nginx
  #   container_name: nginx
  #   ports:
  #     - 443:443
  #   volumes:
  #     - ssl:/etc/porkcron:ro
  #   depends_on:
  #     - porkcron

volumes:
  ssl:
